### ISSUE TITLE
Supports proprietary driver installation for ATI/AMD, but not NVIDIA

### ISSUE THREAD

**Issue by rsharo** [rsharo/steamos_docker#9]
The project has `steamos_ati`, but no `steamos_nvidia`.  Would be nice to have both.

**Comment by rsharo** [comment]
@jcorrado Opened this issue to track your NVIDIA enhancement.

Please feel free to post any NVIDIA-specific comments here.

**Comment by jcorrado** [comment]
@rsharo I just pushed 92ab1e8 in my ``ISSUE-2`` branch.  No build support yet but you can see the simple approach I took, with design notes in the issue ticket.  Comments always welcome!

Makefile updates to follow.

**Comment by rsharo** [comment]
Issue addressed by the recent merge of PR #12
